config/routes.rb
Rails.application.routes.draw do

  post 'line_items/increase_quantity' => 'line_items#increase_quantity'
  post 'line_items/decrease_quantity' => 'line_items#decrease_quantity'
  resources :line_items, only: [:create, :destroy]
  resources :categories, :users, :sessions, :orders
  get 'search_suggestions' => 'products#search_suggestions', as: :search_suggestions

  resources :products do
    resources :comments
  end

  get 'cart' => 'carts#show'
  delete 'cart.:id' => 'carts#destroy'

  namespace :admin do
    resources :categories, :users, :products, :spoiled_foods
    resources :recipes do
      patch 'edit_weight' => 'recipes#edit_weight'
    end
    resources :foods do
      get 'cancel' => 'foods#cancel'
    end
    resources :orders do
      collection do
        get 'download_check_pdf'
      end
    end
    resources :reports do
      collection do
        get 'download_success_orders_pdf'
        get 'download_cancel_porducts_pdf'
        get 'download_foods_pdf'
      end
    end
  end

  get 'admin' => 'admin/admin#index'
  root 'pages#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     #   end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :line_items

  enum status: [:"Новый", :"В обработке", :"Выполнен", :"Отменен"]

  validates :user, :status, presence: true

  self.per_page = 50

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  def total_amount
    orders.to_a.sum { |order| order.total_price }
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  def index
    @orders = Order.page(params[:page]).order(:status)
  end

  def show
    @line_items = @order.line_items
  end

  def edit
  end

  def update
    @user = @order.user
    if @order.update(order_params)
      # UserMailer.order_status_change(@order, @order.user).deliver_later
      if @order.status == "Выполнен"
        @order.line_items.each do |li|
          li.product.recipes.each do |recipe|
            food = Food.find(recipe.food)
            food.weight -= (recipe.weight * li.quantity)
            food.save
          end
        end
      end
      redirect_to [:admin, @order]
    else
      flash[:alert] = "Попробуйте еще раз..."
      redirect_to :back
    end
  end

  def download_check_pdf
    @order = Order.find(params[:order])
    if @order.status == "Выполнен"
      output = Admin::CheckReport.new.to_pdf(@order)
      send_data output, type: 'application/pdf', filename: "check_#{@order.id}.pdf"
    else
      flash[:alert] = "Заказ не выполнен"
      redirect_to :back
    end
  end

  private

    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:status)
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user
  before_action :set_order, only: [:show]

  def show
    @line_items = @order.line_items
  end

  def create
    @cart = current_cart
    @order = Order.new
    @order.add_line_items_from_cart(@cart)
    @order.status = :"Новый"
    @order.user = current_user
    if @cart.line_items.empty?
      flash[:alert] = "Корзина пустая, для заказа выберите продукт"
      redirect_to products_path
      return
    end
    if @order.save
      # UserMailer.order_status_change(@order, @order.user).deliver_later
      Cart.destroy(session[:cart_id])
      session[:cart_id] = nil
      flash[:success] = "Заказ выполнен!"
      redirect_to root_path
    else
      @cart = current_cart
      flash[:alert] = "Что-то пошло не так, сообщите в поддержку"
      redirect_to :back
    end
  end

  private

    def set_order
      @order = Order.find(params[:id])
    end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_form.html.erb
<%= form_for([:admin, @order]) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <% @order.errors.full_messages.each do |message| %>
        <div class="alert alert-danger alert-dismissible fade in" role=alert>
          <button type=button class=close data-dismiss=alert aria-label=Close>
            <span aria-hidden=true>&times;</span>
          </button>
          <%= message %>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.select(:status, Order.statuses.to_a.map{ |w| [w[0].humanize, w[0]] }, {}, { class: "form-control" }) %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary btn-block", value: "Изменить статус" %>
  </div>
<% end %>

app/views/admin/orders/_list_line_items.html.erb
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Фото</th>
        <th>Продукт</th>
        <th>Количество</th>
        <th>Цена</th>
      </tr>
    </thead>
    <tbody>
      <% @line_items.each do |li| %>
        <tr>
          <td><%= image_tag li.product.image_url(:small) if li.product.image? %></td>
          <td><%= link_to li.product.title, product_path(li.product) %></td>
          <td><%= li.quantity %></td>
          <td><%= number_to_currency(li.product.price, unit: "") %> грн</td>
        </tr>
      <% end %>
      <tr>
        <td>Общая сумма:</td>
        <td><%= number_to_currency(order_total_price, unit: "") %> грн</td>
      </tr>
    </tbody>
  </table>
</div>

app/views/admin/orders/_table_index_each.html.erb
<div class="table-responsive">
  <table class="table table-striped table-hover vertical-align">
    <thead>
      <tr>
        <th>#</th>
        <th>Статус выполнения</th>
        <th>Дата заказа</th>
        <th>Пользователь</th>
        <th>Сумма</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <%= content_tag :tr,
          class: case order.status
          when "Новый"
            "warning"
          when "В обработке"
            "active"
          when "Выполнен"
            "success"
          else "Отменен"
            "danger"
          end do %>
          <td><%= link_to order.id, [:admin, order] %></td>
          <td><%= order.status.humanize %></td>
          <td><%= order.created_at.strftime("%d-%m-%Y %H:%M") %></td>
          <td><%= link_to order.user.name, user_path(order.user), target: "_blank" %></td>
          <td><%= number_to_currency(order.total_price, unit: "") %> грн</td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>
<div class="paginate">
  <%= will_paginate @orders, renderer: BootstrapPagination::Rails %>
</div>

app/views/admin/orders/edit.html.erb
<h2>Смена статуса заказа</h2>

<%= render 'form' %>
<div class="col-xs-4">
  <%= link_to 'Отмена', admin_orders_path, class: "btn btn-danger btn-block" %>
</div>

app/views/admin/orders/index.html.erb
<h2>Заказы</h2>

<%= render "table_index_each" %>

app/views/admin/orders/show.html.erb
<p>
  Номер заказа: #<%= @order.id %>
</p>
<%= link_to download_check_pdf_admin_orders_path(order: @order), class: "btn pull-right" do %>
  <span class="glyphicon glyphicon-save-file" aria-hidden="true"></span>
  Чек
<% end %>
<p>
  Статус выполнения:
  <%= @order.status.humanize %>
  <%= link_to "изменить",  '#', "data-target": "#modal_order_status", "data-toggle": "modal"  %>
</p>

<p>
  Пользователь:
  <%= link_to @order.user.name, user_path(@order.user), target: "_blank" %>
</p>

<%= render "admin/orders/list_line_items" %>

<div id='<%= "modal_order_status" %>'class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Смена статуса заказа #<%= @order.id %></h4>
      </div>
      <div class="modal-body">
        <%= render "form", order: @order %>
      </div>
    </div>
  </div>
</div>