config/routes.rb
Rails.application.routes.draw do

  post 'line_items/increase_quantity' => 'line_items#increase_quantity'
  post 'line_items/decrease_quantity' => 'line_items#decrease_quantity'
  resources :line_items, only: [:create, :destroy]
  resources :categories, :users, :sessions, :orders
  get 'search_suggestions' => 'products#search_suggestions', as: :search_suggestions

  resources :products do
    resources :comments
  end

  get 'cart' => 'carts#show'
  delete 'cart.:id' => 'carts#destroy'

  namespace :admin do
    resources :categories, :users, :products, :spoiled_foods
    resources :recipes do
      patch 'edit_weight' => 'recipes#edit_weight'
    end
    resources :foods do
      get 'cancel' => 'foods#cancel'
    end
    resources :orders do
      collection do
        get 'download_check_pdf'
      end
    end
    resources :reports do
      collection do
        get 'download_success_orders_pdf'
        get 'download_cancel_porducts_pdf'
        get 'download_foods_pdf'
      end
    end
  end

  get 'admin' => 'admin/admin#index'
  root 'pages#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     #   end
end

app/models/product.rb
class Product < ActiveRecord::Base
  before_destroy :ensure_not_referenced

  belongs_to :category
  has_many :line_items
  has_many :comments, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :foods, through: :recipes

  validates :title, presence: true,
                    uniqueness: true
  validates :price, presence: true
  validates :image_url, presence: true
  validates :category, presence: true

  mount_uploader :image, ProductUploader

  self.per_page = 6

  private

    def self.search(query)
      where('title ILIKE ? OR description ILIKE ?', "%#{query}%", "%#{query}%")
    end

    def self.search_for_ajax(query)
      where('title ILIKE ? OR description ILIKE ?', "%#{query}%", "%#{query}%").select(:id, :title)
    end

    def ensure_not_referenced
      if line_items.empty?
        true
      else
        errors.add(:base, "Позиция уже существует.")
        false
      end
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :get_collect_categories, except: [:index, :show, :destroy]
  before_action :check_admin
  before_action :get_foods, except: [:show, :index, :destroy]

  def index
    @category = Category.where(id: params[:category]).first if params[:category].present?
    @products = if @category.present?
                  @category.products.order(:title)
                else
                  Product.all.order(:title)
                end
  end

  def show
    @recipes = @product.recipes.order(:id)
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Блюдо добавлено!"
      redirect_to [:admin, @product]
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      flash[:success] = "Блюдо обновлено"
      redirect_to [:admin, @product]
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    flash[:success] = "Блюдо удалено"
    redirect_to admin_products_url
  end

  private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :description, :price, :image, :category_id, food_ids: [])
    end

    def get_foods
      @foods = Food.all
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show]

  def index
    @category = Category.where(id: params[:category]).first if params[:category].present?
    @products = if params[:query].present?
                  Product.search(params[:query]).page(params[:page]).order(created_at: "DESC")
                else
                  if @category.present?
                    @category.products.page(params[:page]).order(created_at: "DESC")
                  else
                    Product.page(params[:page]).order(created_at: "DESC")
                  end
                end
  end

  def show
    @recipes = @product.recipes.order(:id)
  end

  def search_suggestions
    results = if params[:query].present?
                Product.search_for_ajax(params[:query])
              else
                []
              end
    render json: results
  end

  private

    def set_product
      @product = Product.find(params[:id])
    end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for([:admin, @product]) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <% @product.errors.full_messages.each do |message| %>
        <div class="alert alert-danger alert-dismissible fade in" role=alert>
          <button type=button class=close data-dismiss=alert aria-label=Close>
            <span aria-hidden=true>&times;</span>
          </button>
          <%= message %>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, "Название" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price, "Цена" %>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image_url, "Изображение" %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :category_id, "Категория" %>
    <%= f.collection_select(:category_id, @categoies.order(title: :asc), :id, :title, {}, class: "form-control") %>
  </div>
  <div class="checkbox-list">
    <%= f.label :food_id, "Ингредиенты", class: "label-check-boxes" %><br>
    <%= f.collection_check_boxes(:food_ids, @foods.order(title: :asc) || [], :id, :title) %>
  </div>
  <div class="col-xs-8 form-group">
    <%= f.submit class: "btn btn-primary btn-block", value: "Отправить" %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<%= render 'form' %>

<div class="col-xs-4">
  <%= link_to 'Отмена', admin_product_path(@product), class: "btn btn-danger btn-block" %>
</div>

app/views/admin/products/index.html.erb
<% if @category.present? %>
  <h2>Блюдо: <%= @category.title %></h2>
<% else %>
  <h2>Все блюда</h2>
<% end %>
<%= link_to 'Новое блюдо', new_admin_product_path, class: "btn btn-default btn-sm new-item-button" %>

<div class="table-responsive">
  <table class="table table-striped table-hover vertical-align">
    <thead>
      <tr>
        <th>Название</th>
        <th>Цена</th>
        <th>Фото</th>
        <th>Категория</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= link_to product.title, [:admin, product] %></td>
          <td><%= number_to_currency(product.price, unit: "") %> грн</td>
          <td><%= image_tag product.image_url(:small) if product.image? %></td>
          <td><%= product.category.title %></td>
          <td>
            <%= link_to edit_admin_product_path(product) do %>
              <span class="glyphicon glyphicon-pencil text-muted" aria-hidden="true"></span>
            <% end %>
          </td>
          <td>
            <%= link_to [:admin, product], method: :delete, data: { confirm: 'Вы уверены?' } do %>
              <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/products/new.html.erb
<h2>Новое блюдо</h2>

<%= render 'form' %>
<div class="col-xs-4">
  <%= link_to 'Отмена', admin_products_path, class: "btn btn-danger btn-block" %>
</div>

app/views/admin/products/show.html.erb
<div class="col-xs-4">
  <%= image_tag @product.image_url(:middle), class: "img-responsive" if @product.image? %>
</div>
<div class="col-xs-8">
  <h3><%= @product.title %></h3>
  <h4 class="text-danger text-right"><%= number_to_currency(@product.price, unit: "") %> грн</h4>

<h4>Ингредиенты</h4>
<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Название</th>
        <th>Вес, кг</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @recipes.each_with_index do |recipe, index| %>
        <tr>
          <td><%= index+1 %></td>
          <td><%= recipe.food.title %></td>
          <td><%= number_to_currency(recipe.weight, unit: "", precision: 3) %></td>
            <td>
              <%= link_to "редактировать вес", '#', recipe_id: recipe, "data-target": "#modal_recipe_#{recipe.id}", "data-toggle": "modal"  %>
            </td>
        </tr>

        <div id='<%= "modal_recipe_#{recipe.id}" %>'class="modal fade">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Редактировать вес ингредиента: <%= recipe.food.title %></h4>
              </div>
              <div class="modal-body">
                <%= render "admin/recipes/edit", recipe: recipe %>
              </div>
            </div>
          </div>
        </div>

      <% end %>
    </tbody>
  </table>
</div>

</div>
<div class="col-xs-12">
  <%= link_to 'Редактировать', edit_admin_product_path(@product), class: "btn btn-default pull-right" %>
</div>