config/routes.rb
Rails.application.routes.draw do

  post 'line_items/increase_quantity' => 'line_items#increase_quantity'
  post 'line_items/decrease_quantity' => 'line_items#decrease_quantity'
  resources :line_items, only: [:create, :destroy]
  resources :categories, :users, :sessions, :orders
  get 'search_suggestions' => 'products#search_suggestions', as: :search_suggestions

  resources :products do
    resources :comments
  end

  get 'cart' => 'carts#show'
  delete 'cart.:id' => 'carts#destroy'

  namespace :admin do
    resources :categories, :users, :products, :spoiled_foods
    resources :recipes do
      patch 'edit_weight' => 'recipes#edit_weight'
    end
    resources :foods do
      get 'cancel' => 'foods#cancel'
    end
    resources :orders do
      collection do
        get 'download_check_pdf'
      end
    end
    resources :reports do
      collection do
        get 'download_success_orders_pdf'
        get 'download_cancel_porducts_pdf'
        get 'download_foods_pdf'
      end
    end
  end

  get 'admin' => 'admin/admin#index'
  root 'pages#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     #   end
end

app/models/product.rb
class Product < ActiveRecord::Base
  before_destroy :ensure_not_referenced

  belongs_to :category
  has_many :line_items
  has_many :comments, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :foods, through: :recipes

  validates :title, presence: true,
                    uniqueness: true
  validates :price, presence: true
  validates :image_url, presence: true
  validates :category, presence: true

  mount_uploader :image, ProductUploader

  self.per_page = 6

  private

    def self.search(query)
      where('title ILIKE ? OR description ILIKE ?', "%#{query}%", "%#{query}%")
    end

    def self.search_for_ajax(query)
      where('title ILIKE ? OR description ILIKE ?', "%#{query}%", "%#{query}%").select(:id, :title)
    end

    def ensure_not_referenced
      if line_items.empty?
        true
      else
        errors.add(:base, "Позиция уже существует.")
        false
      end
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :get_collect_categories, except: [:index, :show, :destroy]
  before_action :check_admin
  before_action :get_foods, except: [:show, :index, :destroy]

  def index
    @category = Category.where(id: params[:category]).first if params[:category].present?
    @products = if @category.present?
                  @category.products.order(:title)
                else
                  Product.all.order(:title)
                end
  end

  def show
    @recipes = @product.recipes.order(:id)
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Блюдо добавлено!"
      redirect_to [:admin, @product]
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      flash[:success] = "Блюдо обновлено"
      redirect_to [:admin, @product]
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    flash[:success] = "Блюдо удалено"
    redirect_to admin_products_url
  end

  private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :description, :price, :image, :category_id, food_ids: [])
    end

    def get_foods
      @foods = Food.all
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show]

  def index
    @category = Category.where(id: params[:category]).first if params[:category].present?
    @products = if params[:query].present?
                  Product.search(params[:query]).page(params[:page]).order(created_at: "DESC")
                else
                  if @category.present?
                    @category.products.page(params[:page]).order(created_at: "DESC")
                  else
                    Product.page(params[:page]).order(created_at: "DESC")
                  end
                end
  end

  def show
    @recipes = @product.recipes.order(:id)
  end

  def search_suggestions
    results = if params[:query].present?
                Product.search_for_ajax(params[:query])
              else
                []
              end
    render json: results
  end

  private

    def set_product
      @product = Product.find(params[:id])
    end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.erb
<div class="col-sm-6 col-md-4">
  <div class="thumbnail">
    <%= link_to (image_tag product.image_url(:big)), product_path(product), class: "img-responsive" if product.image? %>
    <div class="caption">
      <h3 class="text-center text-muted"><%= link_to product.title, product_path(product) %></h3>
        <h4 class="text-danger text-center"><%= number_to_currency(product.price, unit: "") %> грн</h4>
        <p><%= button_to 'Купить', line_items_path(product_id: product), class: 'btn btn-success btn-block' %></p>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<% if @category.present? %>
  <h2 class="text-warning text-center"><%= @category.title %></h2>
<% else %>
  <h2 class="text-warning text-center">Все продукты</h2>
<% end %>

<%= render @products %>
<div class="clearfix"></div>
<div class="paginate">
  <%= will_paginate @products, renderer: BootstrapPagination::Rails %>
</div>

app/views/products/show.html.erb
<div class="col-xs-4">
  <%= image_tag @product.image_url(:middle), class: "img-responsive" if @product.image? %>
</div>
<div class="col-xs-8">
  <h3><%= @product.title %></h3>
  <h4 class="text-danger text-right"><%= number_to_currency(@product.price, unit: "") %> грн</h4>
  <h4>Ингредиенты</h4>
  <div class="table-responsive">
    <table class="table">
      <tbody>
        <% @recipes.each do |recipe| %>
          <tr>
            <td><%= recipe.food.title %></td>
            <td><%= (recipe.weight*1000).to_i %> г</td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <p class="text-right">Общий вес: <%= @recipes.to_a.sum {|i| i.weight*1000 } %> г</p>
  </div>
  <p><%= button_to 'Купить', line_items_path(product_id: @product), class: 'btn btn-success btn-block' %></p>
</div>
<div class="clearfix"></div>
<div class="col-md-12">
  <% if @product.comments.present? %>
    <h4>Комментарии к блюду</h4>
  <% else %>
    <h4>Комментариев еще нет</h4>
  <% end %>
  <ul class="media-list">
    <%= render @product.comments %>
  </ul>
  <%= render "comments/form" %>
</div>